name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run lint --if-present
      - name: "Build"
        run: npm run build --if-present
      - name: "Test"
        run: npm run test --if-present
      - name: "Deploy"
        if: github.ref == 'refs/heads/master'
        run: npm run deploy
        env:
          AIRTABLE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AIRTABLE_PERSONAL_ACCESS_TOKEN }}
